apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas | default 4 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-{{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-{{ .Release.Name }}
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profile | default "development" | quote }}
            - name: MANAGEMENT_SERVER_PORT
              value: {{ .Values.managementServerPort | default 8081 }}
            - name: REST_MAX_PAGE_SIZE
              value: {{ .Values.maxPageSize | default 100 }}
            - name: AUTH0_AUDIENCE
              value: {{ .Values.auth0Audience | default "https://api.iperka.com/vacations/" | quote }}
            - name: AUTH0_DOMAIN
              value: {{ .Values.auth0Domain | default "https://iperka.eu.auth0.com/" | quote }}
            - name: AUTH0_CLIENT_ID
              value: {{ .Values.auth0ClientId | default "MY_CLIENT_ID" | quote }}
            - name: AUTH0_CLIENT_SECRET
              value: {{ .Values.auth0ClientSecret | default "MY_CLIENT_SECRET" | quote }}
            - name: MONGODB_URI
              value: {{ .Values.mongodbUrl | default "mongodb://localhost:27017/" | quote }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodbDatabase | default "vacations-api-production" | quote }}
            - name: API_DOCS_ENABLED
              value: {{ .Values.apiDocsEnabled| default true | quote }}
            - name: API_DOCS_SHOW_ACTUATOR
              value: {{ .Values.apiDocsShowActuator | default false | quote }}
            - name: SWAGGER_UI_ENABLED
              value: {{ .Values.swaggerUiEnabled | default true | quote }}
            - name: SWAGGER_API_DOCS_PATH
              value: {{ .Values.swaggerUiApiDocsPath | default "../openapi/v3" | quote }}
            - name: SWAGGER_UI_OAUTH2_REDIRECT_URL
              value:  {{ .Values.swaggerUiOAuth2RedirectUrl | default "/oauth2-redirect.html" | quote }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.contextPath | default "/" | quote }}
            - name: API_SERVER_URL
              value: {{ .Values.apiServerUrl | default "https://api.vacations.iperka.com/v1/" | quote }}
            - name: MAIL_HOST
              value: {{ .Values.mailHost | default "localhost" | quote }}
            - name: MAIL_PORT
              value: {{ .Values.mailPort | default 25 }}
            - name: MAIL_USERNAME
              value: {{ .Values.mailUsername | default "myUser" | quote }}
            - name: MAIL_PASSWORD
              value: {{ .Values.mailPassword | default "myPassword" | quote }}
            - name: MAIL_SMTP_AUTH
              value: {{ .Values.mailSmtpAuth | default true | quote }}
            - name: MAIL_SMTP_STARTTLS_ENABLED
              value: {{ .Values.mailSmtpStarttlsEnalbed | default true | quote }}
            - name: MAIL_FROM_ADDRESS
              value: {{ .Values.mailFromAddress | default "no-reply@iperka.com" | quote }}
            - name: MAIL_FROM_NAME
              value: {{ .Values.mailFromName | default "iperka" | quote }}
          image: ghcr.io/iperka/vacations-api:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.managementServerPort | default 8081 }}
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: container-0
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
            - containerPort: {{ .Values.managementServerPort | default 8081 }}
              name: {{ .Values.managementServerPort | default 8081 }}tcp
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.managementServerPort | default 8081 }}
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---